// Socket event names — keep in sync with server/src/socket/events.js
export const EVENTS = {
  ROOM_JOIN: 'room:join',
  ROOM_LEAVE: 'room:leave',
  ROOM_STATE: 'room:state',
  ROOM_CLOSED: 'room:closed',
  PRESENCE_UPDATE: 'presence:update',
  CODE_CHANGE: 'code:change',
  CODE_UPDATE: 'code:update',
  CODE_SYNC_REQUEST: 'code:sync-request',
  CODE_SYNC_RESPONSE: 'code:sync-response',
  CURSOR_MOVE: 'cursor:move',
  CURSOR_UPDATE: 'cursor:update',
  SELECTION_CHANGE: 'selection:change',
  SELECTION_UPDATE: 'selection:update',
  CHAT_SEND: 'chat:send',
  CHAT_MESSAGE: 'chat:message',
  CHAT_HISTORY: 'chat:history',
  PROBLEM_CHANGE: 'problem:change',
  PROBLEM_UPDATE: 'problem:update',
  EXECUTION_START: 'execution:start',
  EXECUTION_RESULT: 'execution:result',
  MEMBER_REMOVED: 'member:removed',
  ERROR: 'error',
};
